# Generated by Django 3.2.7 on 2021-10-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_rename_timetable_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(editable=False)),
                ('time_modified', models.DateTimeField(editable=False)),
                ('attached_file', models.FileField(upload_to='')),
                ('content', models.TextField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.class')),
            ],
            options={
                'ordering': ['time_created', 'time_modified'],
            },
        ),
        migrations.CreateModel(
            name='ClassAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(editable=False)),
                ('time_modified', models.DateTimeField(editable=False)),
                ('content', models.TextField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.class')),
            ],
            options={
                'ordering': ['time_created', 'time_modified'],
            },
        ),
    ]
