# Generated by Django 3.2.7 on 2021-10-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_classannouncement_classcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcontent',
            name='attached_file',
            field=models.FileField(upload_to='documents/%class_id'),
        ),
    ]
