# Generated by Django 3.2.7 on 2021-10-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_alter_classcontent_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classannouncement',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='classannouncement',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classcontent',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='classcontent',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
