# Generated by Django 3.2.7 on 2021-10-13 16:16

import Courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_auto_20211011_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcontent',
            name='attached_file',
            field=models.FileField(blank=True, upload_to=Courses.models.class_content_location),
        ),
    ]
