# Generated by Django 3.2.7 on 2021-11-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_alter_classcontent_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcontent',
            name='attached_file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
