# Generated by Django 3.2.7 on 2021-11-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0009_alter_classcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcontent',
            name='attached_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
