# Generated by Django 3.2.7 on 2021-11-28 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0010_alter_classcontent_attached_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 0, 0)),
        ),
    ]
