# Generated by Django 3.2.7 on 2021-10-06 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.lecturer'),
        ),
    ]
