# Generated by Django 3.2.7 on 2021-10-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_announcement_author_id'),
        ('Home', '0003_announcement_title'),
    ]

    operations = [
    ]
