# Generated by Django 3.2.7 on 2021-10-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_merge_20211013_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
