# Generated by Django 3.2.7 on 2021-11-22 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_announcement_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='time_announced',
        ),
        migrations.AddField(
            model_name='announcement',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 21, 44, 6, 443129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
