# Generated by Django 3.2.7 on 2021-11-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20211123_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
