# Generated by Django 3.2.7 on 2021-11-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_announcement_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
