# Generated by Django 3.2.5 on 2021-11-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_announcement_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
