# Generated by Django 3.2.7 on 2021-11-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_announcement_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='time_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
