# Generated by Django 3.2.7 on 2021-11-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_announcement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
