# Generated by Django 3.2.7 on 2021-10-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
        ('User', '0002_auto_20211003_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.major'),
        ),
    ]
