# Generated by Django 3.2.7 on 2021-10-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
        ('User', '0003_student_major_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ManyToManyField(to='Courses.Class'),
        ),
    ]
