# Generated by Django 3.2.7 on 2021-11-28 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0010_alter_classcontent_attached_file'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
                ('is_true', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_written', models.BooleanField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_description', models.TextField(blank=True, null=True)),
                ('test_name', models.CharField(max_length=100)),
                ('publish_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('available_time_after_deadline', models.DurationField(default=datetime.timedelta(seconds=21600))),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('is_overdue', models.BooleanField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.test')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_ans', models.TextField(blank=True, null=True)),
                ('choice_ans', models.ManyToManyField(blank=True, to='Classwork.MultipleChoiceOption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.question')),
                ('student_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.studenttest')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.test'),
        ),
        migrations.AddField(
            model_name='multiplechoiceoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.question'),
        ),
    ]
