# Generated by Django 3.2.7 on 2021-10-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Courses', '0007_alter_classcontent_attached_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Option', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_written', models.BooleanField()),
                ('question', models.TextField()),
                ('solution', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.test')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_ans', models.TextField(blank=True, null=True)),
                ('choice_ans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Classwork.multiplechoiceoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.question')),
                ('student_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.studenttest')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.test'),
        ),
        migrations.AddField(
            model_name='multiplechoiceoption',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.question'),
        ),
    ]
