# Generated by Django 3.2.7 on 2021-10-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoiceoption',
            old_name='Option',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='multiplechoiceoption',
            old_name='Question',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='solution',
        ),
        migrations.AddField(
            model_name='multiplechoiceoption',
            name='is_true',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
