# Generated by Django 3.2.7 on 2021-10-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0002_auto_20211014_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
