# Generated by Django 3.2.7 on 2021-10-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0003_test_test_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='start_time',
            new_name='publish_time',
        ),
    ]
