# Generated by Django 3.2.7 on 2021-10-17 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0004_rename_start_time_test_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='available_time_after_deadline',
            field=models.DurationField(default=datetime.timedelta(seconds=21600)),
        ),
    ]
