# Generated by Django 3.2.7 on 2021-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0005_test_available_time_after_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='choice_ans',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='choice_ans',
            field=models.ManyToManyField(blank=True, to='Classwork.MultipleChoiceOption'),
        ),
    ]
