# Generated by Django 3.2.7 on 2021-11-27 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0006_auto_20211121_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
