# Generated by Django 3.2.7 on 2021-11-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0007_studenttest_submit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
